import type { AssessmentLoop, Finding, SystemGraph } from "@northwall/shared";

export const targetProfile = {
  name: "AcmePay Security Operations",
  type: "Owned SOC workspace",
  stack: ["Microsoft Sentinel", "CrowdStrike", "GitHub", "Postgres", "Stripe webhooks", "Jira"],
  scope: ["siem://acmepay", "edr://acmepay", "repo://acmepay", "jira://security"],
  budget: "35 min / human approval required",
};

export const systemGraph: SystemGraph = {
  confidence: 94,
  lastUpdatedAt: 1_777_897_200_000,
  nodes: [
    { id: "siem", label: "SIEM incident queue", kind: "service", risk: "high" },
    { id: "edr", label: "Endpoint telemetry", kind: "integration", risk: "high" },
    { id: "identity", label: "Identity events", kind: "auth", risk: "critical" },
    { id: "cloud", label: "Cloud audit logs", kind: "service", risk: "medium" },
    { id: "app", label: "Customer app", kind: "app", risk: "medium" },
    { id: "repo", label: "GitHub code context", kind: "integration", risk: "medium" },
    { id: "owners", label: "Service owners", kind: "service", risk: "low" },
    { id: "tickets", label: "Response work items", kind: "integration", risk: "low" },
  ],
  edges: [
    { id: "siem-edr", source: "siem", target: "edr", label: "alert evidence" },
    { id: "siem-identity", source: "siem", target: "identity", label: "user context" },
    { id: "identity-cloud", source: "identity", target: "cloud", label: "session activity" },
    { id: "cloud-app", source: "cloud", target: "app", label: "affected service" },
    { id: "app-repo", source: "app", target: "repo", label: "code owner lookup" },
    { id: "repo-owners", source: "repo", target: "owners", label: "ownership" },
    { id: "owners-tickets", source: "owners", target: "tickets", label: "handoff" },
  ],
};

export const expertTeam = [
  {
    name: "Nova",
    role: "Incident Cartographer",
    focus: "Maps alerts, entities, assets, owners, and investigation paths.",
    status: "Investigation graph ready",
  },
  {
    name: "Rhea",
    role: "Alert Triage Agent",
    focus: "Cuts duplicate signals, groups related alerts, and ranks urgency.",
    status: "Triage complete",
  },
  {
    name: "Kade",
    role: "Threat Investigator",
    focus: "Checks identity, endpoint, cloud, and repo context for a coherent case.",
    status: "Correlating evidence",
  },
  {
    name: "Mira",
    role: "Response Planner",
    focus: "Drafts response tasks with owners, approvals, and rollback notes.",
    status: "Plan ready",
  },
  {
    name: "Ilya",
    role: "Control Verifier",
    focus: "Checks whether compensating controls already reduced the risk.",
    status: "Verification running",
  },
  {
    name: "Vera",
    role: "Human Review Agent",
    focus: "Prepares the analyst handoff and keeps risky actions behind approval.",
    status: "Preparing handoff",
  },
];

export const loops: AssessmentLoop[] = [
  {
    id: "loop-1",
    title: "Map the incident",
    strategy: "Correlate SIEM, EDR, identity, cloud, repo, and ownership context.",
    agents: ["Nova", "Rhea"],
    findingsAdded: 1,
    graphChanges: 11,
    nextHypothesis: "Identity event and endpoint alert point to the same privileged workflow.",
    status: "complete",
  },
  {
    id: "loop-2",
    title: "Triage likely blast radius",
    strategy: "Separate noisy alerts from assets, users, and services with real exposure.",
    agents: ["Rhea", "Mira", "Kade"],
    findingsAdded: 3,
    graphChanges: 6,
    nextHypothesis: "Cloud session and service owner data can narrow response scope.",
    status: "complete",
  },
  {
    id: "loop-3",
    title: "Verify controls",
    strategy: "Check safe evidence sources and existing controls before escalation.",
    agents: ["Ilya", "Mira"],
    findingsAdded: 1,
    graphChanges: 3,
    nextHypothesis: "Evidence supports two high-confidence response tasks.",
    status: "running",
  },
  {
    id: "loop-4",
    title: "Rank and hand off",
    strategy: "Remove weak signals, assign owners, and define verification steps.",
    agents: ["Vera"],
    findingsAdded: 0,
    graphChanges: 1,
    nextHypothesis: "Stop after response plan generation unless new evidence appears.",
    status: "queued",
  },
];

export const findings: Finding[] = [
  {
    id: "BG-104",
    title: "Privileged session touched billing export path after unusual login",
    severity: "high",
    confidence: "high",
    status: "open",
    owner: "Security Engineering",
    affectedNodeIds: ["identity", "app", "repo"],
    evidence: [
      "Identity events show a new device for an admin user.",
      "Endpoint telemetry puts the same user on a managed laptop.",
      "Code ownership maps the touched billing export path to the Payments team.",
    ],
    businessImpact: "The case may be benign, but it crosses identity, endpoint, and sensitive billing code in one short window.",
    fixPlan: "Ask the owner to verify the session, check device posture, and review the export route permissions before closing the case.",
    verificationStep: "Attach identity, EDR, and code-owner evidence to the work item; require analyst approval before closure.",
    cwe: "CWE-862",
    asvs: "ASVS 4.3.1",
    kev: false,
  },
  {
    id: "BG-117",
    title: "Payment webhook alert lacks owner and rollback path",
    severity: "high",
    confidence: "medium",
    status: "in_progress",
    owner: "Payments",
    affectedNodeIds: ["siem", "app", "owners"],
    evidence: [
      "SIEM alert is tied to the Stripe webhook route.",
      "Service ownership points to Payments, not the platform queue.",
      "No rollback note is attached to the current ticket template.",
    ],
    businessImpact: "A real payment incident can sit in the wrong queue while billing state changes continue.",
    fixPlan: "Create a Payments-owned response task with webhook replay checks, rollback owner, and customer-impact notes.",
    verificationStep: "Reviewer confirms owner assignment and rollback path before the work item is marked ready.",
    cwe: "CWE-345",
    asvs: "ASVS 13.2.1",
    kev: false,
  },
  {
    id: "BG-122",
    title: "Dependency signal affects service in active incident path",
    severity: "medium",
    confidence: "high",
    status: "ready_for_review",
    owner: "Platform",
    affectedNodeIds: ["repo", "cloud"],
    evidence: [
      "Lockfile contains a vulnerable transitive package below the patched advisory range.",
      "The package is pulled into the service linked to the active alert.",
      "CISA KEV enrichment raised response priority.",
    ],
    businessImpact: "The package issue is no longer just backlog hygiene because it sits on the current incident graph.",
    fixPlan: "Update the parent package, regenerate the lockfile, and attach the SBOM diff to the response task.",
    verificationStep: "Confirm the affected package is absent from the production dependency graph.",
    cve: "CVE-2025-47281",
    cwe: "CWE-1321",
    asvs: "ASVS 14.2.1",
    kev: true,
  },
  {
    id: "BG-131",
    title: "Low-confidence alert kept out of the response queue",
    severity: "medium",
    confidence: "medium",
    status: "open",
    owner: "SOC Analyst",
    affectedNodeIds: ["siem", "edr"],
    evidence: [
      "Alert pattern matched an older detection rule.",
      "Endpoint and identity context did not support escalation.",
    ],
    businessImpact: "Without filtering, analysts waste time on a weak signal while higher-confidence work waits.",
    fixPlan: "Keep the evidence on the case, but do not create an owner task unless a second signal appears.",
    verificationStep: "Reviewer checks that no response task was created for the weak signal.",
    cwe: "CWE-1032",
    asvs: "ASVS 7.1.1",
    kev: false,
  },
];

export const evidenceTimeline = [
  ["09:41", "Scope gate", "Owned systems confirmed; response actions require approval."],
  ["09:43", "Graph update", "Mapped 8 nodes across SIEM, EDR, identity, cloud, app, repo, owners, and work items."],
  ["09:47", "Agent handoff", "Triage Agent and Threat Investigator started parallel evidence review."],
  ["09:52", "Finding", "BG-104 promoted to high confidence after identity and endpoint correlation."],
  ["09:57", "Finding", "BG-117 kept at medium confidence pending Payments owner confirmation."],
  ["10:04", "Owner handoff", "BG-122 moved to review with SBOM verification step."],
];
