import type { AssessmentLoop, Finding, SystemGraph } from "@northwall/shared";

export const targetProfile = {
  name: "AcmePay SaaS",
  type: "Owned application",
  stack: ["Next.js", "Hono API", "Postgres", "Stripe webhooks", "GitHub Actions"],
  scope: ["localhost", "repo://acmepay", "sbom://acmepay-web"],
  budget: "35 min / 30 rpm",
};

export const systemGraph: SystemGraph = {
  confidence: 94,
  lastUpdatedAt: 1_777_897_200_000,
  nodes: [
    { id: "web", label: "Web app", kind: "app", risk: "medium" },
    { id: "api", label: "API service", kind: "api", risk: "high" },
    { id: "auth", label: "Session auth", kind: "auth", risk: "high" },
    { id: "billing", label: "Stripe webhook", kind: "integration", risk: "medium" },
    { id: "postgres", label: "Postgres", kind: "database", risk: "medium" },
    { id: "deps", label: "npm packages", kind: "package", risk: "high" },
    { id: "ci", label: "GitHub Actions", kind: "service", risk: "low" },
    { id: "secrets", label: "Env secrets", kind: "secret", risk: "critical" },
  ],
  edges: [
    { id: "web-api", source: "web", target: "api", label: "REST calls" },
    { id: "web-auth", source: "web", target: "auth", label: "session cookie" },
    { id: "api-db", source: "api", target: "postgres", label: "queries" },
    { id: "api-stripe", source: "api", target: "billing", label: "webhook handler" },
    { id: "api-secrets", source: "api", target: "secrets", label: "env access" },
    { id: "ci-deps", source: "ci", target: "deps", label: "install/build" },
  ],
};

export const expertTeam = [
  {
    name: "Nova",
    role: "System Cartographer",
    focus: "Maps routes, data flow, trust boundaries, and risky graph paths.",
    status: "Graph pass complete",
  },
  {
    name: "Rhea",
    role: "Code Auditor",
    focus: "Reviews auth, input handling, webhook logic, and access checks.",
    status: "Reviewing API handlers",
  },
  {
    name: "Kade",
    role: "Dependency Analyst",
    focus: "Checks SBOM, advisories, lockfile drift, and KEV relevance.",
    status: "2 packages elevated",
  },
  {
    name: "Mira",
    role: "Auth & Access Analyst",
    focus: "Tests role boundaries, session lifetime, and tenant isolation.",
    status: "Auth matrix ready",
  },
  {
    name: "Ilya",
    role: "Runtime Verifier",
    focus: "Runs safe local probes against approved routes with rate limits.",
    status: "Loop 3 running",
  },
  {
    name: "Vera",
    role: "Risk Reviewer",
    focus: "Deduplicates weak signals and turns evidence into owner-ready work.",
    status: "Prioritizing queue",
  },
];

export const loops: AssessmentLoop[] = [
  {
    id: "loop-1",
    title: "Map the system",
    strategy: "Parse app routes, package manifests, env usage, and auth boundaries.",
    agents: ["Nova", "Rhea"],
    findingsAdded: 1,
    graphChanges: 11,
    nextHypothesis: "Webhook and session code share privileged paths.",
    status: "complete",
  },
  {
    id: "loop-2",
    title: "Target likely weak paths",
    strategy: "Focus static checks on tenant isolation, webhook verification, and secret handling.",
    agents: ["Rhea", "Mira", "Kade"],
    findingsAdded: 3,
    graphChanges: 6,
    nextHypothesis: "Stripe retry path may bypass expected ownership checks.",
    status: "complete",
  },
  {
    id: "loop-3",
    title: "Verify safely in runtime",
    strategy: "Run approved local probes against auth and billing routes under rate limit.",
    agents: ["Ilya", "Mira"],
    findingsAdded: 1,
    graphChanges: 3,
    nextHypothesis: "Runtime evidence supports two high-confidence findings.",
    status: "running",
  },
  {
    id: "loop-4",
    title: "Rank and assign",
    strategy: "Remove weak signals, map to ASVS/CWE, assign owners, and define verification steps.",
    agents: ["Vera"],
    findingsAdded: 0,
    graphChanges: 1,
    nextHypothesis: "Stop after remediation plan generation unless new evidence appears.",
    status: "queued",
  },
];

export const findings: Finding[] = [
  {
    id: "BG-104",
    title: "Tenant ownership check missing on invoice export",
    severity: "high",
    confidence: "high",
    status: "open",
    owner: "Backend",
    affectedNodeIds: ["api", "auth", "postgres"],
    evidence: [
      "Route map links `/api/invoices/export` to account-scoped data.",
      "Static review found account id read from request body before membership check.",
      "Safe local probe received a 200 on mismatched tenant fixture.",
    ],
    businessImpact: "A user could access another workspace's billing export if they can guess or obtain an account id.",
    fixPlan: "Resolve workspace membership from the authenticated session first, then ignore account ids supplied by clients for export queries.",
    verificationStep: "Add integration tests for cross-tenant export attempts and require 403 for mismatched workspace fixtures.",
    cwe: "CWE-862",
    asvs: "ASVS 4.3.1",
    kev: false,
  },
  {
    id: "BG-117",
    title: "Webhook signature failure falls through to retry handler",
    severity: "high",
    confidence: "medium",
    status: "in_progress",
    owner: "Payments",
    affectedNodeIds: ["api", "billing", "secrets"],
    evidence: [
      "Stripe webhook route has a verified branch and a retry branch.",
      "Retry handler accepts normalized event payload before returning signature failure.",
      "Runtime verifier stopped before side effects and recorded branch reachability only.",
    ],
    businessImpact: "A malformed webhook could reach payment retry logic and create noisy billing state.",
    fixPlan: "Return immediately on signature failure before payload normalization, then isolate retry handling behind verified event objects.",
    verificationStep: "Replay unsigned webhook fixtures and assert no retry, invoice, or event-log write occurs.",
    cwe: "CWE-345",
    asvs: "ASVS 13.2.1",
    kev: false,
  },
  {
    id: "BG-122",
    title: "Transitive package has active exploitation signal",
    severity: "medium",
    confidence: "high",
    status: "ready_for_review",
    owner: "Platform",
    affectedNodeIds: ["deps", "ci"],
    evidence: [
      "Lockfile contains a vulnerable transitive package below the patched advisory range.",
      "Package is pulled into server build path, not only dev tooling.",
      "KEV enrichment raised remediation priority.",
    ],
    businessImpact: "Build and server paths inherit a known vulnerable dependency that should be removed from the deployable graph.",
    fixPlan: "Update the parent package, regenerate the lockfile, and fail CI on the vulnerable range.",
    verificationStep: "Run dependency audit and SBOM diff in CI; confirm the affected package is absent from production dependency graph.",
    cve: "CVE-2025-47281",
    cwe: "CWE-1321",
    asvs: "ASVS 14.2.1",
    kev: true,
  },
  {
    id: "BG-131",
    title: "Session cookie lacks explicit same-site policy in staging",
    severity: "medium",
    confidence: "medium",
    status: "open",
    owner: "Frontend",
    affectedNodeIds: ["web", "auth"],
    evidence: [
      "Auth config sets secure cookies but leaves SameSite implicit in staging.",
      "Runtime verifier observed cookie attributes on approved localhost route.",
    ],
    businessImpact: "Cross-site request boundaries are less explicit across staging and production-like environments.",
    fixPlan: "Set SameSite=Lax for standard app sessions and document exceptions for OAuth callback paths.",
    verificationStep: "Add cookie attribute assertions to auth callback tests.",
    cwe: "CWE-1275",
    asvs: "ASVS 3.4.2",
    kev: false,
  },
];

export const evidenceTimeline = [
  ["09:41", "Scope gate", "Owned sample app confirmed; third-party targets disabled."],
  ["09:43", "Graph update", "Mapped 8 nodes and 6 edges across web, API, auth, database, billing, CI, and secrets."],
  ["09:47", "Agent handoff", "Code Auditor and Auth Analyst started parallel review of protected routes."],
  ["09:52", "Finding", "BG-104 promoted to high confidence after safe local verification."],
  ["09:57", "Finding", "BG-117 kept at medium confidence pending payment retry fixture coverage."],
  ["10:04", "Remediation", "BG-122 moved to review with CI verification step."],
];
