import type { AssessmentLoop, Finding, SystemGraph } from "@northwall/shared";

export const targetProfile = {
  name: "AcmePay AppSec Orchestration",
  type: "Owned AppSec mission workspace",
  stack: ["GitHub", "Postgres", "Stripe webhooks", "Jira", "Microsoft Sentinel roadmap", "CrowdStrike roadmap"],
  scope: ["repo://acmepay", "owner://acmepay", "jira://security", "siem://roadmap", "edr://roadmap"],
  budget: "35 min / human approval required",
};

export const systemGraph: SystemGraph = {
  confidence: 94,
  lastUpdatedAt: 1_777_897_200_000,
  nodes: [
    { id: "repo", label: "GitHub source context", kind: "integration", risk: "medium" },
    { id: "app", label: "Customer app", kind: "app", risk: "medium" },
    { id: "auth", label: "Auth boundary", kind: "auth", risk: "critical" },
    { id: "deps", label: "Dependency graph", kind: "package", risk: "high" },
    { id: "ci", label: "CI and release controls", kind: "integration", risk: "medium" },
    { id: "config", label: "Runtime configuration", kind: "service", risk: "medium" },
    { id: "owners", label: "Service owners", kind: "service", risk: "low" },
    { id: "tickets", label: "Owner handoff work", kind: "integration", risk: "low" },
  ],
  edges: [
    { id: "repo-app", source: "repo", target: "app", label: "source context" },
    { id: "app-auth", source: "app", target: "auth", label: "auth boundary" },
    { id: "repo-deps", source: "repo", target: "deps", label: "package evidence" },
    { id: "repo-ci", source: "repo", target: "ci", label: "release guardrails" },
    { id: "app-config", source: "app", target: "config", label: "runtime context" },
    { id: "repo-owners", source: "repo", target: "owners", label: "ownership" },
    { id: "owners-tickets", source: "owners", target: "tickets", label: "handoff" },
  ],
};

export const expertTeam = [
  {
    name: "Nova",
    role: "System Cartographer",
    focus: "Maps routes, packages, controls, owners, and remediation paths.",
    status: "AppSec graph ready",
  },
  {
    name: "Rhea",
    role: "Auth Boundary Agent",
    focus: "Reviews auth, tenant, session, middleware, and permission-sensitive paths.",
    status: "Boundary review complete",
  },
  {
    name: "Kade",
    role: "Dependency Analyst",
    focus: "Checks package evidence, lockfile exposure, ownership, and release risk.",
    status: "Correlating package evidence",
  },
  {
    name: "Mira",
    role: "CI/Config Analyst",
    focus: "Reviews pipeline, runtime configuration, environment references, and guardrails.",
    status: "Plan ready",
  },
  {
    name: "Ilya",
    role: "Control Verifier",
    focus: "Checks whether compensating controls already reduce AppSec risk.",
    status: "Verification running",
  },
  {
    name: "Vera",
    role: "Human Review Agent",
    focus: "Prepares owner handoff and keeps risky actions behind approval.",
    status: "Preparing handoff",
  },
];

export const loops: AssessmentLoop[] = [
  {
    id: "loop-1",
    title: "Map the AppSec graph",
    strategy: "Correlate source, routes, auth, dependencies, CI, config, and ownership context.",
    agents: ["Nova", "Rhea"],
    findingsAdded: 1,
    graphChanges: 11,
    nextHypothesis: "Auth boundary and service ownership point to the same high-risk route.",
    status: "complete",
  },
  {
    id: "loop-2",
    title: "Run parallel specialists",
    strategy: "Split auth, dependency, ownership, config, and CI work across focused agents.",
    agents: ["Rhea", "Mira", "Kade"],
    findingsAdded: 3,
    graphChanges: 6,
    nextHypothesis: "Dependency and CI context can narrow which owners need action.",
    status: "complete",
  },
  {
    id: "loop-3",
    title: "Verify controls",
    strategy: "Check safe source evidence and existing controls before escalation.",
    agents: ["Ilya", "Mira"],
    findingsAdded: 1,
    graphChanges: 3,
    nextHypothesis: "Evidence supports two high-confidence owner handoffs.",
    status: "running",
  },
  {
    id: "loop-4",
    title: "Rank and hand off",
    strategy: "Remove weak signals, assign owners, and define verification steps.",
    agents: ["Vera"],
    findingsAdded: 0,
    graphChanges: 1,
    nextHypothesis: "Stop after owner handoff generation unless new evidence appears.",
    status: "queued",
  },
];

export const findings: Finding[] = [
  {
    id: "BG-104",
    title: "Billing export route crosses auth and ownership boundaries",
    severity: "high",
    confidence: "high",
    status: "open",
    owner: "Security Engineering",
    affectedNodeIds: ["auth", "app", "repo"],
    evidence: [
      "Auth middleware and billing export route sit in the same request path.",
      "Tenant ownership checks are owned by Security Engineering.",
      "Code ownership maps the touched billing export path to the Payments team.",
    ],
    businessImpact: "The path touches sensitive billing exports and shared auth logic, so weak ownership can delay remediation.",
    fixPlan: "Ask the owner to verify tenant checks, route permissions, and billing export ownership before release.",
    verificationStep: "Attach route, auth, and code-owner evidence to the work item; require analyst approval before closure.",
    cwe: "CWE-862",
    asvs: "ASVS 4.3.1",
    kev: false,
  },
  {
    id: "BG-117",
    title: "Payment webhook route lacks owner and rollback path",
    severity: "high",
    confidence: "medium",
    status: "in_progress",
    owner: "Payments",
    affectedNodeIds: ["app", "config", "owners"],
    evidence: [
      "Source inventory maps the Stripe webhook route.",
      "Service ownership points to Payments, not the platform queue.",
      "No rollback note is attached to the current ticket template.",
    ],
    businessImpact: "A payment security issue can sit in the wrong queue while billing state changes continue.",
    fixPlan: "Create a Payments-owned response task with webhook replay checks, rollback owner, and customer-impact notes.",
    verificationStep: "Reviewer confirms owner assignment and rollback path before the work item is marked ready.",
    cwe: "CWE-345",
    asvs: "ASVS 13.2.1",
    kev: false,
  },
  {
    id: "BG-122",
    title: "Dependency signal affects a service on the AppSec graph",
    severity: "medium",
    confidence: "high",
    status: "ready_for_review",
    owner: "Platform",
    affectedNodeIds: ["repo", "deps"],
    evidence: [
      "Lockfile contains a vulnerable transitive package below the patched advisory range.",
      "The package is pulled into a service on the approved mission graph.",
      "CISA KEV enrichment raised response priority.",
    ],
    businessImpact: "The package issue is no longer just backlog hygiene because it sits on the current AppSec graph.",
    fixPlan: "Update the parent package, regenerate the lockfile, and attach the SBOM diff to the response task.",
    verificationStep: "Confirm the affected package is absent from the production dependency graph.",
    cve: "CVE-2025-47281",
    cwe: "CWE-1321",
    asvs: "ASVS 14.2.1",
    kev: true,
  },
  {
    id: "BG-131",
    title: "Low-confidence signal kept out of the owner queue",
    severity: "medium",
    confidence: "medium",
    status: "open",
    owner: "AppSec Reviewer",
    affectedNodeIds: ["repo", "ci"],
    evidence: [
      "Pattern matched an older dependency signal.",
      "Graph and ownership context did not support escalation.",
    ],
    businessImpact: "Without filtering, reviewers waste time on a weak signal while higher-confidence handoffs wait.",
    fixPlan: "Keep the evidence on the case, but do not create an owner task unless a second signal appears.",
    verificationStep: "Reviewer checks that no response task was created for the weak signal.",
    cwe: "CWE-1032",
    asvs: "ASVS 7.1.1",
    kev: false,
  },
];

export const evidenceTimeline = [
  ["09:41", "Scope gate", "Owned systems confirmed; response actions require approval."],
  ["09:43", "Graph update", "Mapped 8 nodes across repo, app, auth, dependencies, CI, config, owners, and work items."],
  ["09:47", "Agent handoff", "Auth Boundary Agent and Dependency Analyst started parallel evidence review."],
  ["09:52", "Handoff", "BG-104 promoted to high confidence after route and auth correlation."],
  ["09:57", "Handoff", "BG-117 kept at medium confidence pending Payments owner confirmation."],
  ["10:04", "Owner handoff", "BG-122 moved to review with SBOM verification step."],
];
